data:extend({
  {
    type = "fluid",
    name = "lithium-brine",
    default_temperature = 15,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0, g=0.54, b=0.6},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__Beyond__/graphics/icons/lithium-brine-fluid.png",
    order = "p",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "ammonia",
    fuel_value = "8MJ",
    default_temperature = 20,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.2, g=0.2, b=0.4},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__Beyond__/graphics/icons/ammonia.png",
    order = "p-b",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "ammonium-nitrate",
    default_temperature = 20,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.2, g=0.2, b=0.4},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__Beyond__/graphics/icons/ammonium-nitrate.png",
    order = "p-c",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "nitric-acid",
    default_temperature = 20,
    max_temperature = 100,
    heat_capacity = "1KJ",
    base_color = {r=0.2, g=0.2, b=0.4},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__Beyond__/graphics/icons/nitric-acid.png",
    order = "p-d",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "hydrogen",
    default_temperature = 20,
    max_temperature = 20,
    heat_capacity = "1KJ",
    base_color = {r=0.2, g=0.2, b=0.4},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__Beyond__/graphics/icons/hydrogen.png",
    order = "p-a",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "liquid-hydrogen",
    default_temperature = -253,
    max_temperature = -253,
    heat_capacity = "1KJ",
    base_color = {r=0.2, g=0.2, b=0.4},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__Beyond__/graphics/icons/liquid-hydrogen.png",
    order = "p-e",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "liquid-oxygen",
    default_temperature = -220,
    max_temperature = -220,
    heat_capacity = "1KJ",
    base_color = {r=0.2, g=0.2, b=0.4},
    flow_color = {r=0.7, g=0.7, b=0.7},
    icon = "__Beyond__/graphics/icons/liquid-oxygen.png",
    order = "p-f",
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  }
})
