require("prototypes.categories")
require("prototypes.item-groups")
require("prototypes.items")
require("prototypes.weapon-items")
require("prototypes.noise-layers")
require("prototypes.entities")
require("prototypes.weapon-entities")
require("prototypes.reactor-entity")
require("prototypes.recipes")
require("prototypes.weapon-recipes")
require("prototypes.reactor-recipes")
require("prototypes.technology")

require("prototypes.resources")
require("prototypes.autoplace-controls")